# fly.toml app configuration file generated for rummikub on 2023-07-23T21:53:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rummikub"
primary_region = "waw"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
